[toolchain]

[features]
resolution = true
skip-lint = false
test-sbf = []

[programs.localnet]
spl_airdrop = "4gjGVTWDi19sBVS6oj4oskGyvennpyoxYju3rtUt4Qdo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = '/home/boosik/.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"